name: TestabilityWorkshop
options:
  bundleIdPrefix: com.practice
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

targets:
  TestabilityWorkshop:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj/**"
          - TestabilityWorkshopTests/**
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  TestabilityWorkshopTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: TestabilityWorkshopTests
    dependencies:
      - target: TestabilityWorkshop
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/TestabilityWorkshop.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/TestabilityWorkshop"
        BUNDLE_LOADER: "$(TEST_HOST)"
